version: "3"

services:
  db:
    image: postgres:11
    container_name: postgres_db
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - sanic-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - "8000"
    env_file:
      - ./.env
    container_name: web_app
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - sanic-network

networks:
  sanic-network:
    driver: bridge