version: "3"

services:
  db:
    image: postgres:11
    container_name: postgres_db
    restart: on-failure
    env_file: .env
    networks:
      - sanic-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - "8000"
    command: >
      bash -c "cd migrations/
      && ./liquibase migrate
      && cd .. && python3 main.py"
    ports:
      - "8000:8000"
    env_file: .env
    container_name: web_app
    restart: on-failure
    networks:
      - sanic-network

networks:
  sanic-network:
    driver: bridge